# Generated by Django 6.1 on 2026-08-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('automation', 'Automation'), ('embedded', 'Embedded Systems'), ('data', 'Data & Analytics'), ('career', 'Career'), ('tutorial', 'Tutorial'), ('other', 'Other')], max_length=30)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.CharField(default='Code & Control', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
