# Generated by Django 6.1 on 2026-08-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_remove_blogpost_category_delete_blogcategory_and_more'),
        ('portfolio', '0002_project_status'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_resources',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='resources.resource'),
        ),
    ]
