# Generated by Django 6.1 on 2026-08-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='in_progress', max_length=20),
        ),
    ]
