# Generated by Django 6.1 on 2026-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tutorial', 'Tutorial'), ('guide', 'Guide'), ('cheatsheet', 'Cheat Sheet'), ('ebook', 'eBook'), ('code', 'Source Code'), ('template', 'Template'), ('other', 'Other')], max_length=30)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('pdf', 'PDF'), ('code', 'Code'), ('video', 'Video'), ('external', 'External Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_url', models.URLField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='resources/images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
